version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:80"
    restart: always
    volumes:
      - .:/var/www/html
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    environment:
      - DB_HOST=db
      - DB_NAME=biblioteca
      - DB_USER=root
      - DB_PASSWORD=root
      - JWT_SECRET_KEY=sua_chave_secreta
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 5s
      timeout: 10s
      retries: 10
